services:
  server:
    container_name: server
    build: ./server
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    env_file:
      - ./server/.env
    depends_on:
      - database
  client:
    build: ./client
    container_name: client
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3001:3000"
    stdin_open: true
    tty: true
  database:
    image: mysql:latest
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
