services:
  e-store:
    container_name: ${WEB_HOST}
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: remote_host=172.17.0.1
  estoredb:
    image: mysql:latest
    container_name: ${DB_HOST}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"